import type { Incident, Monitor, OverviewStats } from "./types";

function series(base: number, spread: number, len = 28, seed = 1) {
  let s = seed * 9301;
  return Array.from({ length: len }, () => {
    s = (s * 9301 + 49297) % 233280;
    const r = s / 233280;
    return Math.round(base + (r - 0.5) * spread);
  });
}

const now = Date.UTC(2026, 7, 21, 16, 30, 0);
const iso = (minutesAgo: number) => new Date(now - minutesAgo * 60_000).toISOString();

export const mockMonitors: Monitor[] = [
  {
    id: "mon_checkout",
    name: "Checkout API",
    url: "https://api.acme.io/v2/checkout",
    method: "POST",
    region: "us-east-1",
    intervalSeconds: 30,
    status: "up",
    responseTimeMs: 142,
    uptime30d: 99.985,
    lastCheckedAt: iso(0.4),
    latencySeries: series(142, 60, 28, 3),
  },
  {
    id: "mon_auth",
    name: "Auth Gateway",
    url: "https://auth.acme.io/token",
    method: "POST",
    region: "eu-west-1",
    intervalSeconds: 30,
    status: "degraded",
    responseTimeMs: 684,
    uptime30d: 99.62,
    lastCheckedAt: iso(0.7),
    latencySeries: series(560, 320, 28, 7),
  },
  {
    id: "mon_search",
    name: "Search Cluster",
    url: "https://api.acme.io/v2/search",
    method: "GET",
    region: "us-west-2",
    intervalSeconds: 60,
    status: "up",
    responseTimeMs: 208,
    uptime30d: 99.94,
    lastCheckedAt: iso(1.2),
    latencySeries: series(210, 90, 28, 11),
  },
  {
    id: "mon_webhooks",
    name: "Webhook Dispatcher",
    url: "https://hooks.acme.io/dispatch",
    method: "POST",
    region: "ap-south-1",
    intervalSeconds: 60,
    status: "down",
    responseTimeMs: 0,
    uptime30d: 98.11,
    lastCheckedAt: iso(0.9),
    latencySeries: series(320, 260, 28, 17),
  },
  {
    id: "mon_billing",
    name: "Billing Worker",
    url: "https://api.acme.io/v2/billing/health",
    method: "GET",
    region: "us-east-1",
    intervalSeconds: 120,
    status: "up",
    responseTimeMs: 96,
    uptime30d: 100,
    lastCheckedAt: iso(2.1),
    latencySeries: series(98, 40, 28, 23),
  },
  {
    id: "mon_cdn",
    name: "Edge CDN",
    url: "https://cdn.acme.io/ping",
    method: "HEAD",
    region: "global",
    intervalSeconds: 30,
    status: "up",
    responseTimeMs: 41,
    uptime30d: 99.999,
    lastCheckedAt: iso(0.3),
    latencySeries: series(44, 22, 28, 29),
  },
  {
    id: "mon_graphql",
    name: "GraphQL Edge",
    url: "https://api.acme.io/graphql",
    method: "POST",
    region: "eu-central-1",
    intervalSeconds: 60,
    status: "up",
    responseTimeMs: 176,
    uptime30d: 99.87,
    lastCheckedAt: iso(1.6),
    latencySeries: series(180, 70, 28, 31),
  },
  {
    id: "mon_reports",
    name: "Reports Export",
    url: "https://api.acme.io/v2/reports/export",
    method: "GET",
    region: "us-east-1",
    intervalSeconds: 300,
    status: "paused",
    responseTimeMs: 0,
    uptime30d: 99.4,
    lastCheckedAt: iso(240),
    latencySeries: series(400, 120, 28, 37),
  },
];

export const mockIncidents: Incident[] = [
  {
    id: "inc_4831",
    monitorId: "mon_webhooks",
    monitorName: "Webhook Dispatcher",
    title: "Webhook dispatcher returning 503 in ap-south-1",
    severity: "critical",
    state: "identified",
    startedAt: iso(46),
    resolvedAt: null,
    durationMinutes: 46,
    affectedRegions: ["ap-south-1"],
    rootCause: "Queue consumer pool saturated after retry storm",
    timeline: [
      {
        id: "ev_1",
        at: iso(46),
        state: "investigating",
        author: "Sentinel Bot",
        message: "3 consecutive failed checks from ap-south-1 — HTTP 503. Incident opened automatically.",
      },
      {
        id: "ev_2",
        at: iso(41),
        state: "investigating",
        author: "Priya N.",
        message: "Acknowledged. Consumer lag spiking to 42k messages; scaling workers 4 → 12.",
      },
      {
        id: "ev_3",
        at: iso(28),
        state: "identified",
        author: "Priya N.",
        message: "Root cause identified: retry storm from a partner integration exhausted the consumer pool. Rate limit applied at the edge.",
      },
      {
        id: "ev_4",
        at: iso(9),
        state: "identified",
        author: "Sentinel Bot",
        message: "Error rate down from 96% → 31%. Awaiting 5 clean checks before moving to monitoring.",
      },
    ],
  },
  {
    id: "inc_4829",
    monitorId: "mon_auth",
    monitorName: "Auth Gateway",
    title: "Elevated p95 latency on token endpoint (eu-west-1)",
    severity: "major",
    state: "monitoring",
    startedAt: iso(180),
    resolvedAt: null,
    durationMinutes: 180,
    affectedRegions: ["eu-west-1"],
    rootCause: "Session store failover increased round-trip time",
    timeline: [
      {
        id: "ev_1",
        at: iso(180),
        state: "investigating",
        author: "Sentinel Bot",
        message: "p95 latency crossed 600ms threshold for 5 minutes.",
      },
      {
        id: "ev_2",
        at: iso(150),
        state: "identified",
        author: "Marco L.",
        message: "Session store replica failover in progress; reads served from secondary AZ.",
      },
      {
        id: "ev_3",
        at: iso(60),
        state: "monitoring",
        author: "Marco L.",
        message: "Primary restored. Latency trending to baseline — monitoring for 2 hours before resolve.",
      },
    ],
  },
  {
    id: "inc_4812",
    monitorId: "mon_search",
    monitorName: "Search Cluster",
    title: "Search shard timeouts during reindex",
    severity: "minor",
    state: "resolved",
    startedAt: iso(1490),
    resolvedAt: iso(1418),
    durationMinutes: 72,
    affectedRegions: ["us-west-2"],
    rootCause: "Reindex job ran without throttling",
    timeline: [
      {
        id: "ev_1",
        at: iso(1490),
        state: "investigating",
        author: "Sentinel Bot",
        message: "Intermittent 504s detected on /v2/search.",
      },
      {
        id: "ev_2",
        at: iso(1455),
        state: "identified",
        author: "Dana K.",
        message: "Nightly reindex saturating shard IO. Throttle applied.",
      },
      {
        id: "ev_3",
        at: iso(1418),
        state: "resolved",
        author: "Dana K.",
        message: "All checks green for 30 minutes. Incident resolved; throttling added to the reindex job permanently.",
      },
    ],
  },
  {
    id: "inc_4804",
    monitorId: "mon_checkout",
    monitorName: "Checkout API",
    title: "TLS certificate expiring in 6 days",
    severity: "minor",
    state: "resolved",
    startedAt: iso(4300),
    resolvedAt: iso(4180),
    durationMinutes: 120,
    affectedRegions: ["us-east-1"],
    rootCause: "Auto-renew hook disabled during migration",
    timeline: [
      {
        id: "ev_1",
        at: iso(4300),
        state: "investigating",
        author: "Sentinel Bot",
        message: "Certificate expiry warning raised by SSL check.",
      },
      {
        id: "ev_2",
        at: iso(4180),
        state: "resolved",
        author: "Sam R.",
        message: "Auto-renew re-enabled and certificate rotated.",
      },
    ],
  },
];

export const mockOverview: OverviewStats = {
  uptimePercent: 99.962,
  uptimeTrend: 0.04,
  avgLatencyMs: 184,
  latencyTrend: -7.2,
  activeIncidents: mockIncidents.filter((i) => i.state !== "resolved").length,
  monitorsTotal: mockMonitors.length,
  monitorsPaused: mockMonitors.filter((m) => m.status === "paused").length,
  latencySeries: Array.from({ length: 32 }, (_, i) => {
    const p50 = series(170, 70, 32, 5)[i]!;
    return {
      t: new Date(now - (31 - i) * 15 * 60_000).toISOString(),
      p50,
      p95: p50 + 120 + ((i * 37) % 90),
    };
  }),
};
